services:
  # ollama-webui:
  #   image: ghcr.io/open-webui/open-webui:main
  #   container_name: ollama-webui
  #   volumes:
  #     - /mnt/ollama/ollama-webui:/app/backend/data
  #   depends_on:
  #     - ollama
  #   ports:
  #     - "3000:8080"
  #   environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
  #     - OLLAMA_BASE_URLS=http://host.docker.internal:11434 #comma separated ollama hosts
  #     - WEBUI_NAME=AAUNO
  #     - WEBUI_SECRET_KEY=aauno
  #   extra_hosts:
  #     - host.docker.internal:host-gateway
  #   restart: unless-stopped
  #   networks:
  #     - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - /mnt/ollama/ollama:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    networks:
      - ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  ollama:
    name: ollama
    driver: bridge
    external: true