services:
  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - /nfs/ollama-webui:/app/backend/data
    ports:
      - "3000:8080"
    environment: 
      - OLLAMA_BASE_URLS=http://host.docker.internal:11434 
      - WEBUI_NAME=AAUNO
      - WEBUI_SECRET_KEY=aauno
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - ollama-webui

networks:
  ollama-webui:
    name: ollama-webui
    driver: bridge
    external: false