services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    environment:
    - SEARXNG_BASE_URL=https://searx.aauno.io/
    ports:
      - "8080:8080"
    volumes:
      - /nfs/searxng:/etc/searxng:rw
    restart: unless-stopped
    networks:
      - searxng

networks:
  searxng:
    name: searxng
    external: false