services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    ports:
      - "8080:8080"
    volumes:
      - /nfs/searxng:/etc/searxng:rw
    restart: unless-stopped
    networks:
      - searxng
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE

networks:
  searxng:
    name: searxng
    external: false