services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "8080:8080"
    volumes:
      - /nfs/searxng:/etc/searxng:rw
    restart: unless-stopped
    networks:
      - searxng

networks:
  searxng:
    external: false